spring.application.name=ApiGateway


# ===============================
# Server Configuration
# ===============================
server.port=8088

# ===============================
# Spring Cloud Gateway Routes
# ===============================

# Employee Service
spring.cloud.gateway.routes[0].id=employee
spring.cloud.gateway.routes[0].uri=lb://EMPLOYEE
spring.cloud.gateway.routes[0].predicates[0]=Path=/employee/**

# Address Service
spring.cloud.gateway.routes[1].id=address
spring.cloud.gateway.routes[1].uri=lb://ADDRESS
spring.cloud.gateway.routes[1].predicates[0]=Path=/address/**

# Job Service
spring.cloud.gateway.routes[2].id=job
spring.cloud.gateway.routes[2].uri=lb://JOB-DESCRIPTION
spring.cloud.gateway.routes[2].predicates[0]=Path=/job/**

# ===============================
# Eureka Configuration
# ===============================
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
